"""truck can be added with chassis

Revision ID: 25c46dfeeeaf
Revises: bef72302e518
Create Date: 2024-10-18 14:35:40.312988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25c46dfeeeaf'
down_revision: Union[str, None] = 'bef72302e518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
