"""truck can be added with chassis1

Revision ID: 97f012eb6e93
Revises: 25c46dfeeeaf
Create Date: 2024-10-18 14:37:44.681494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f012eb6e93'
down_revision: Union[str, None] = '25c46dfeeeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
