"""add truck table add chassis table

Revision ID: d8da2764b229
Revises: fd9d5b5b2fd0
Create Date: 2024-10-17 22:18:26.620330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd8da2764b229'
down_revision: Union[str, None] = 'fd9d5b5b2fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
